version: 2.1
jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo hello

  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo World !

workflows:
   welcome:
    jobs:
      - print-hello
      - print-world

        

