version: 2.1
jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo hello
    
  print-world:
    shell: /bin/sh
    environment:
      BASH_ENV: /etc/profile

    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo World $MY_VAR !
    


workflows:
   welcome:
    jobs:
      - print-hello
      - print-world

        

