version: 2.1
jobs:
  print-hello:
    docker:
      - image: cimg/base:stable

    branches:
      only:
          - main
          
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo "Hello"

  print-world:
    docker:
      - image: cimg/base:stable

     branches:
      only:
          - main

    steps:
     - checkout
     - run: echo "World!"

workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-world
        requires: [print-world]

